version: '3.8'
services:
  api-tests:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=petclinic
      - DB_PASSWORD=petclinic
      - DB_VENDOR=postgres
      - BASE_URL=http://petclinic-app:9966/petclinic
     # - LOKI_URL=http://loki:3100 # uncomment this to run with Loki
    depends_on:
      - postgres
      - petclinic-app
      - grafana
      - loki

  petclinic-app:
    image: springcommunity/spring-petclinic-rest:3.4.3
    ports:
      - "9966:9966"
    environment:
      - SPRING_PROFILES_ACTIVE=spring-data-jpa,postgresql
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_DB=petclinic
    ports:
      - "5432:5432"

  # Loki Stack
  loki:
    image: grafana/loki:3.4.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:12.3.0-18578466485
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki